name: moodmap
description: "An offline-first journaling app that uses AI to analyze daily entries, generating weekly insights and personalized mood gradients."
publish_to: 'none'
version: 0.0.5+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  lottie: ^3.3.2
  pretty_animated_buttons: ^0.0.2
  smooth_page_indicator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: "Inter"
      fonts:
       - asset: "assets/fonts/Inter.ttf"

  assets:
    - "assets/native_splash_light.png"
    - "assets/native_splash_dark.png"
    - "assets/intro_logo/moodmap_logo_light.json"
    - "assets/intro_logo/moodmap_logo_dark.json"
