import 'package:flutter/material.dart';

import '../constants/app_colors.dart';

class AppTheme {
  static ThemeData get lightTheme => ThemeData(
    useMaterial3: true,
    fontFamily: 'Inter',
    scaffoldBackgroundColor: AppColors.lightBg,
    colorScheme: const ColorScheme(
      brightness: Brightness.light,
      primary: AppColors.coreMulberry,
      onPrimary: Color(0xFFFAF0F8),
      primaryContainer: AppColors.mulberryLight,
      onPrimaryContainer: Color(0xFF2A0D20),
      secondary: AppColors.corePetal,
      onSecondary: Color(0xFFFDF2F6),
      secondaryContainer: AppColors.petalLight,
      onSecondaryContainer: Color(0xFF330D1E),
      tertiary: AppColors.coreWisteria,
      onTertiary: Color(0xFFF4F2FC),
      tertiaryContainer: AppColors.wisteriaLight,
      onTertiaryContainer: Color(0xFF1A1838),
      surface: AppColors.lightBg,
      onSurface: AppColors.lightOnSurface,
      onSurfaceVariant: AppColors.lightOnSurfaceVariant,
      surfaceDim: AppColors.lightSurfaceDim,
      surfaceBright: AppColors.lightSurfaceBright,
      surfaceContainerLowest: AppColors.lightSurfaceContainerLowest,
      surfaceContainerLow: AppColors.lightSurfaceContainerLow,
      surfaceContainer: AppColors.lightSurfaceContainer,
      surfaceContainerHigh: AppColors.lightSurfaceContainerHigh,
      surfaceContainerHighest: AppColors.lightSurfaceContainerHighest,
      surfaceTint: Colors.transparent,
      error: AppColors.lightError,
      onError: AppColors.lightOnError,
      errorContainer: AppColors.lightErrorContainer,
      onErrorContainer: AppColors.lightOnErrorContainer,
      outline: AppColors.lightOutline,
      outlineVariant: AppColors.lightOutlineVariant,
      inverseSurface: Color(0xFF2D2A34),
      onInverseSurface: Color(0xFFEEECF5),
      inversePrimary: AppColors.mulberryLight,
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
    ),
  );

  static ThemeData get darkTheme => ThemeData(
    useMaterial3: true,
    fontFamily: 'Inter',
    scaffoldBackgroundColor: AppColors.darkBg,
    colorScheme: const ColorScheme(
      brightness: Brightness.dark,
      primary: AppColors.coreMulberry,
      onPrimary: Color(0xFF1A0A17),
      primaryContainer: AppColors.mulberryDeep,
      onPrimaryContainer: AppColors.mulberryLight,
      secondary: AppColors.corePetal,
      onSecondary: Color(0xFF2A0D1A),
      secondaryContainer: AppColors.petalDeep,
      onSecondaryContainer: AppColors.petalLight,
      tertiary: AppColors.coreWisteria,
      onTertiary: Color(0xFF100E2A),
      tertiaryContainer: AppColors.wisteriaDeep,
      onTertiaryContainer: AppColors.wisteriaLight,
      surface: AppColors.darkBg,
      onSurface: AppColors.darkOnSurface,
      onSurfaceVariant: AppColors.darkOnSurfaceVariant,
      surfaceDim: AppColors.darkSurfaceDim,
      surfaceBright: AppColors.darkSurfaceBright,
      surfaceContainerLowest: AppColors.darkSurfaceContainerLowest,
      surfaceContainerLow: AppColors.darkSurfaceContainerLow,
      surfaceContainer: AppColors.darkSurfaceContainer,
      surfaceContainerHigh: AppColors.darkSurfaceContainerHigh,
      surfaceContainerHighest: AppColors.darkSurfaceContainerHighest,
      surfaceTint: Colors.transparent,
      error: AppColors.darkError,
      onError: AppColors.darkOnError,
      errorContainer: AppColors.darkErrorContainer,
      onErrorContainer: AppColors.darkOnErrorContainer,
      outline: AppColors.darkOutline,
      outlineVariant: AppColors.darkOutlineVariant,
      inverseSurface: Color(0xFFE5E3EB),
      onInverseSurface: Color(0xFF1A1820),
      inversePrimary: AppColors.mulberryDeep,
      shadow: Color(0xFF000000),
      scrim: Color(0xFF000000),
    ),
  );
}
